Repository manuasir/film-recommendator, pull requests merged in 2023-10, with the labels that each got.

#15 Modified README.md
  README.md
Labels: documentation

#14 Added Dockerfile
  .gitignore
  Dockerfile
Labels: enhancement

#19 GitHub Action: Automated PR build
  .github/workflows/pull-request-build.yml
  docker-compose.yml
Labels: enhancement

#17 API
  README.md
  src/database/api.py
  src/database/models/film.py
  src/index.py
Labels: enhancement

#18 API v2
  src/database/api.py
  src/database/models/film.py
  src/index.py
Labels: duplicate, enhancement

#24 Refactor
  src/api/__init__.py
  src/api/api.py
  src/database/api.py
  src/database/connection.py
  src/database/models/film.py
  src/index.py
Labels: enhancement
